name: Publish Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    name: Build Distributions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set Up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - name: Build Release Distributions
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine
          python -m build
          twine check --strict dist/*
      - name: Upload Distributions
        uses: actions/upload-artifact@v7
        with:
          name: release-dists
          path: dist/

  publish-pypi:
    name: Publish To PyPI
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download Distributions
        uses: actions/download-artifact@v8
        with:
          name: release-dists
          path: dist/
      - name: Publish Package Distributions To PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
